// src/routes/auth/login/+page.svelte
<script lang="ts">
  import { loginWithPassword } from '$lib/auth';
  import { goto } from '$app/navigation';
  let email = '';
  let password = '';
  let loading = false;
  let errorMessage = '';

  async function handleLogin() {
    loading = true;
    errorMessage = '';
    try {
      await loginWithPassword(email, password);
      goto('/dashboard'); // Ganti sesuai route tujuanmu
    } catch (e: any) {
      errorMessage = e.message || 'Gagal login, cek email/password.';
    } finally {
      loading = false;
    }
  }
</script>

<div class="auth-container">
  <form on:submit|preventDefault={handleLogin} class="auth-card">
    <h1>Masuk ke Akun</h1>
    
    {#if errorMessage}
      <p class="error">{errorMessage}</p>
    {/if}

    <div class="field">
      <label for="email">Email</label>
      <input type="email" bind:value={email} placeholder="email@contoh.com" required />
    </div>

    <div class="field">
      <label for="password">Password</label>
      <input type="password" bind:value={password} placeholder="••••••••" required />
    </div>

    <button type="submit" disabled={loading}>
      {loading ? 'Sabar ya...' : 'Masuk'}
    </button>

    <p class="footer-text">
      Belum punya akun? <a href="/auth/register">Daftar di sini</a>
    </p>
  </form>
</div>

<style>
  .auth-container {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 80vh;
    background-color: var(--bg-primary);
    font-family: var(--font-main);
  }

  .auth-card {
    background-color: var(--bg-surface);
    padding: var(--space-xl);
    border-radius: var(--radius-md);
    border: 1px solid var(--border-subtle);
    width: 100%;
    max-width: 400px;
  }

  h1 {
    color: var(--text-primary);
    margin-bottom: var(--space-lg);
    font-size: 1.5rem;
  }

  .field {
    margin-bottom: var(--space-lg);
  }

  label {
    display: block;
    color: var(--text-secondary);
    margin-bottom: var(--space-xs);
    font-size: 0.9rem;
  }

  input {
    width: 100%;
    padding: var(--space-md);
    background-color: var(--bg-primary);
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-sm);
    color: var(--text-primary);
    box-sizing: border-box;
  }

  input:focus {
    outline: none;
    border-color: var(--accent);
  }

  button {
    width: 100%;
    padding: var(--space-md);
    background-color: var(--accent);
    color: white;
    border: none;
    border-radius: 25px; /* Biar agak bulat ala medsos sebelah */
    font-weight: bold;
    cursor: pointer;
    transition: background 0.2s;
  }

  button:hover {
    background-color: var(--accent-hover);
  }

  button:disabled {
    opacity: 0.5;
  }

  .error {
    color: #f4212e;
    font-size: 0.85rem;
    margin-bottom: var(--space-md);
  }

  .footer-text {
    color: var(--text-secondary);
    text-align: center;
    margin-top: var(--space-xl);
    font-size: 0.9rem;
  }

  a {
    color: var(--accent);
    text-decoration: none;
  }
</style>

// src/routes/Login.jsx
import { createSignal } from "solid-js";
import { useNavigate } from "@solidjs/router";
import { login } from "../utils/auth";

import { Mail, Lock } from "lucide-solid";

export default function Login() {
  const navigate = useNavigate();

  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      await login({ email: email(), password: password() });
      navigate("/"); // redirect ke home
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="min-h-screen bg-black flex items-center justify-center p-4">
      <div class="bg-zinc-900 rounded-2xl p-6 w-full max-w-md shadow-xl space-y-4 text-white">
        <h2 class="text-xl font-semibold text-center">Login 🔐</h2>

        <form onSubmit={handleSubmit} class="space-y-4">
          {/* Email */}
          <div class="flex items-center gap-2 border border-zinc-700 rounded-lg px-3 py-2">
            <Mail size={18} />
            <input
              type="email"
              placeholder="Email"
              class="bg-transparent flex-1 outline-none text-sm text-white placeholder:text-zinc-500"
              value={email()}
              onInput={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          {/* Password */}
          <div class="flex items-center gap-2 border border-zinc-700 rounded-lg px-3 py-2">
            <Lock size={18} />
            <input
              type="password"
              placeholder="Password"
              class="bg-transparent flex-1 outline-none text-sm text-white placeholder:text-zinc-500"
              value={password()}
              onInput={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          {/* Submit */}
          <button
            type="submit"
            disabled={loading()}
            class="w-full bg-pink-600 hover:bg-pink-500 py-2 rounded-lg font-semibold text-white"
          >
            {loading() ? "Logging in..." : "Login"}
          </button>

          {error() && <p class="text-red-500 text-sm">{error()}</p>}
        </form>

        <p class="text-sm text-zinc-400 text-center">
          Belum punya akun?{" "}
          <a href="/register" class="text-pink-500 hover:underline">
            Register
          </a>
        </p>
      </div>
    </div>
  );
}
