// src/routes/Login.jsx
import { createSignal } from "solid-js";
import { useNavigate } from "@solidjs/router";
import { login } from "../utils/auth";

import { Mail, Lock } from "lucide-solid";

export default function Login() {
  const navigate = useNavigate();

  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      await login({ email: email(), password: password() });
      navigate("/"); // redirect ke home
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="min-h-screen bg-black flex items-center justify-center p-4">
      <div class="bg-zinc-900 rounded-2xl p-6 w-full max-w-md shadow-xl space-y-4 text-white">
        <h2 class="text-xl font-semibold text-center">Login 🔐</h2>

        <form onSubmit={handleSubmit} class="space-y-4">
          {/* Email */}
          <div class="flex items-center gap-2 border border-zinc-700 rounded-lg px-3 py-2">
            <Mail size={18} />
            <input
              type="email"
              placeholder="Email"
              class="bg-transparent flex-1 outline-none text-sm text-white placeholder:text-zinc-500"
              value={email()}
              onInput={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          {/* Password */}
          <div class="flex items-center gap-2 border border-zinc-700 rounded-lg px-3 py-2">
            <Lock size={18} />
            <input
              type="password"
              placeholder="Password"
              class="bg-transparent flex-1 outline-none text-sm text-white placeholder:text-zinc-500"
              value={password()}
              onInput={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          {/* Submit */}
          <button
            type="submit"
            disabled={loading()}
            class="w-full bg-pink-600 hover:bg-pink-500 py-2 rounded-lg font-semibold text-white"
          >
            {loading() ? "Logging in..." : "Login"}
          </button>

          {error() && <p class="text-red-500 text-sm">{error()}</p>}
        </form>

        <p class="text-sm text-zinc-400 text-center">
          Belum punya akun?{" "}
          <a href="/register" class="text-pink-500 hover:underline">
            Register
          </a>
        </p>
      </div>
    </div>
  );
}

// src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { supabase } from '$lib/supabase/client';
  import Button from '$lib/components/Button.svelte';
  import Input from '$lib/components/Input.svelte';
  import Card from '$lib/components/Card.svelte';

  let email = $state('');
  let password = $state('');
  let error = $state('');
  let loading = $state(false);

  async function handleLogin(e: SubmitEvent) {
    e.preventDefault();
    error = '';
    loading = true;

    const { error: authError } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (authError) {
      error = authError.message;
      loading = false;
      return;
    }

    goto('/');
  }
</script>

<div class="login-page">
  <Card class="auth-card">
    <h1>Login</h1>

    {#if error}
      <p class="error">{error}</p>
    {/if}

    <form onsubmit={handleLogin}>
      <Input
        label="Email"
        type="email"
        id="login-email"
        bind:value={email}
        required
        placeholder="your@email.com"
      />

      <Input
        label="Password"
        type="password"
        id="login-password"
        bind:value={password}
        required
        placeholder="••••••••"
      />

      <Button type="submit" variant="primary" disabled={loading}>
        {loading ? 'Logging in...' : 'Login'}
      </Button>
    </form>

    <p class="footer">
      Don't have an account? <a href="/register">Register</a>
    </p>
  </Card>
</div>

<style>
  .login-page {
    display: flex;
    justify-content: center;
    align-items: center;
    flex: 1;
    padding: 2rem;
  }

  :global(.auth-card) {
    width: 100%;
    max-width: 400px;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  h1 {
    font-size: 1.5rem;
    font-weight: bold;
    margin: 0;
    text-align: center;
    letter-spacing: -0.5px;
  }

  form {
    display: flex;
    flex-direction: column;
    gap: 1.2rem;
  }

  .error {
    color: #ff5252;
    font-size: 0.9rem;
    background: rgba(255, 82, 82, 0.1);
    padding: 0.75rem;
    border-radius: var(--radius);
    border: 1px solid rgba(255, 82, 82, 0.2);
  }

  .footer {
    text-align: center;
    font-size: 0.9rem;
    color: var(--text-muted);
    margin: 0;
  }

  .footer a {
    color: var(--text);
    text-decoration: underline;
  }
</style>
